### ISSUE TITLE
Can't find related files in dl.dropboxusercontent.com

### ISSUE THREAD

**Issue by viody** [limingyangpro/Local-Geometric-Consensus-Examples#1]
I'm interested in this work and expect to run the code, but failed to get the resources from dl.dropboxusercontent.com.

**Comment by limingyangpro** [comment]
Hello,
Thanks for pointing out. Please use this link: https://www.dropbox.com/s/xmp6sp2n5y1r2z5/liblgc.a?dl=0

BR,

**Comment by viody** [comment]
Wow that's great ! Thank you for your prompt reply.
